epochs: 32
tokenizer: RN50
lr: 0.001
weight_decay: 0.2
warmup_epochs: 4.25
log_frequency: 200
min_lr: 0
sync_bn: false
lr_schedule: cosine
snapshot_epoch: 32
eval_every_epoch: 1
amp: true
zero_shot_templates: OPENAI_IMAGENET_TEMPLATES
class_names: IMAGENET_CLASSNAMES
backdoor_zero_shot_eval: true
backdoor_zero_shot_templates: OPENAI_IMAGENET_TEMPLATES
backdoor_label: banana
backdoor_label_idx: 954
criterion:
  name: OpenClipLoss
  gather_distributed: true
optimizer:
  name: AdamW
  lr: $lr
  weight_decay: 0
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
vision_model:
  name: VisionTransformerOpenCLIP
  image_size: 224
  output_dim: 512
  layers: 12
  width: 768
  heads: 12
  patch_size: 16
  get_features: true
text_model:
  name: TextTransformer
  context_length: 77
  vocab_size: 49408
  width: 512
  heads: 8
  layers: 12
  output_dim: 512
dataset:
  name: DatasetGenerator
  train_bs: 256
  eval_bs: 512
  n_workers: 8
  train_d_type: ConceptualCaptionsDatasetBlend
  test_d_type: ImageFolder
  test_bd_d_type: ImageNetBlendZeroShot
  train_tf_op: CLIPCC3M
  test_tf_op: CLIPCC3M
  train_path: TODO: Set the path to the Conceptual Captions dataset
  test_path: TODO: Set the path to the ImageNet dataset
  test_bd_path: TODO: Set the path to the ImageNet dataset
  tokenizer: $tokenizer
  poison_rate: 0.001
  test_poison_rate: 1
  backdoor_label_idx: $backdoor_label_idx
  backdoor_label: $backdoor_label
  collate_fn:
    name: None
  alpha: 0.2
  image_trigger: trigger/SIG_noise.pt
  threat_model: single
